include:
  - board: nice_nano//zmk
    shield: A1WJUN-KBD47
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: A1WJUN-KBD47
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: A1WJUN-KBD47_Reset
